

-- 1. 테이블 작성

CREATE TABLE TB_CATEGORY (
   NAME VARCHAR2(10),
   USE_YN CHAR(1) DEFAULT 'Y'
);


-- 2. 테이블 작성

CREATE TABLE TB_CLASS_TYPE
(
   NO VARCHAR2(5) PRIMARY KEY,
   NAME VARCHAR2(10)
);

--3. 1번 문제 테이블에 NAME컬럼에 PRIMARY KEY를 생성하시오
ALTER TABLE TB_CATEGORY MODIFY NAME PRIMARY KEY;
ALTER TABLE TB_CATEGORY RENAME CONSTRAINT SYS_C008680 TO TC_PK ;


--4. TB_CLASS_TYPE 테이블의 NAME 컬럼에 NULL 값이 들어가지 않도록 속성 변경

ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;


--5 . 컬럼 크기 변경

ALTER TABLE TB_CATEGORY MODIFY NAME VARCHAR2(20);
ALTER TABLE TB_CLASS_TYPE MODIFY NAME VARCHAR2(20);

--6. 컬럼 이름 변경


ALTER TABLE TB_CATEGORY DROP COLUMN NAME;
ALTER TABLE TB_CATEGORY DROP COLUMN USE_YN;

ALTER TABLE TB_CATEGORY ADD CATEGORY_NAME VARCHAR2(20);
ALTER TABLE TB_CATEGORY ADD CATEGORY_USE_YN CHAR(1);


ALTER TABLE TB_CLASS_TYPE DROP COLUMN NO;
ALTER TABLE TB_CLASS_TYPE ADD CLASS_TYPE_NO VARCHAR2(5);
ALTER TABLE TB_CLASS_TYPE DROP COLUMN NAME;
ALTER TABLE TB_CLASS_TYPE ADD CLASS_TYPE_NAME VARCHAR2(5);



-- 7. 
 ALTER TABLE CATEGORY RENAME CONSTRAINT TC_PK TO PK_CATEGORY_NAME ;
 ALTER TABLE CLASS_TYPE RENAME CONSTRAINT SYS_C008679 TO PK_CLASS_TYPE_NAME ;
 
 
 --8.
 
 INSERT INTO TB_CATEGORY VALUES ('공학', 'Y');
 INSERT INTO TB_CATEGORY VALUES ('자연과학', 'Y');
 INSERT INTO TB_CATEGORY VALUES ('의학', 'Y');
 INSERT INTO TB_CATEGORY VALUES ('예체능', 'Y');
 INSERT INTO TB_CATEGORY VALUES ('인문사회', 'Y');
 
 
 -- 9.
 ALTER TABLE TB_DEPARTMENT
          ADD CONSTRAINT FK_DEPARTMENT_CATEGORY
               FOREIGN KEY (CATEGORY) REFERENCES TB_CATEGORY (CATEGORY_NAME);
 
 

 -- 10. 
 
 CREATE VIEW VW_TB_STUDENT
 AS (
    SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS FROM TB_STUDENT
 );
 
SELECT * FROM TB_STUDENT;


-- 11.
CREATE VIEW VW_지도면담 AS
SELECT STUDENT_NAME 학생이름, DEPARTMENT_NAME 학과이름,   NVL(PROFESSOR_NAME,'지도교수없음' )지도교수이름 
FROM TB_STUDENT
    LEFT JOIN TB_PROFESSOR P ON COACH_PROFESSOR_NO = PROFESSOR_NO
         JOIN TB_DEPARTMENT D ON p.department_no = d.department_no
         ORDER BY 학과이름;


DROP VIEW VW_지도면담;

SELECT * FROM VW_지도면담; 
SELECT * FROM VW_지도면담 ORDER BY vw_지도면담.department_name;


-- 12

SELECT *FROM TB_STUDENT;
SELECT * FROM TB_DEPARTMENT;
 
 
 CREATE VIEW VW_학과별학생수
 AS 
 SELECT DEPARTMENT_NAME 학과명, COUNT(STUDENT_NAME) "학과별 학생수" FROM TB_STUDENT
        JOIN TB_DEPARTMENT USING (DEPARTMENT_NO) 
        GROUP BY DEPARTMENT_NAME;
 
 
 SELECT * FROM TB_STUDENT;
 DROP VIEW VW_학과별학생수;
 
 
 --13. 
    UPDATE VW_TB_STUDENT SET  STUDENT_NAME ='KKH'
                    WHERE STUDENT_NO ='A213046';
                                
  SELECT * FROM VW_TB_STUDENT;
  
--14. 
CREATE OR REPLACE VIEW VW_TB_STUDENT (학번, 학생이름, 주소)
AS (SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS FROM TB_STUDENT)
WITH READ ONLY;

-- 15
SELECT 과목번호, 과목이름, "누적수강생수(명)"
 FROM (
        SELECT CLASS_NO 과목번호, CLASS_NAME 과목이름, COUNT(*) "누적수강생수(명)"
           FROM TB_GRADE 
            JOIN TB_CLASS USING (CLASS_NO)
        WHERE TERM_NO LIKE '2005%'
             OR TERM_NO LIKE '2006%'
             OR TERM_NO LIKE '2007%'
             OR TERM_NO LIKE '2008%'
             OR TERM_NO LIKE '2009%'
        GROUP BY CLASS_NO, CLASS_NAME
        ORDER BY 3 DESC
        )
WHERE ROWNUM < 4 ;
    
 