

-- 1 

select *  FROM TB_STUDENT;

SELECT RPAD(STUDENT_NAME,10) "학생 이름", STUDENT_ADDRESS  "주소지"
FROM TB_STUDENT;

-- 2.

SELECT STUDENT_NAME, STUDENT_SSN 
FROM TB_STUDENT 
WHERE absence_yn = 'Y'
ORDER BY 2 DESC;



-- 3 
  
  SELECT * FROM TB_STUDENT;
  
  SELECT STUDENT_NAME, STUDENT_NO, STUDENT_ADDRESS
  FROM TB_STUDENT
  WHERE SUBSTR(STUDENT_ADDRESS,1,3) IN ('경기도','강원도')
        AND SUBSTR(STUDENT_NO,1 ,1) IN ('9');



-- 4

SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_PROFESSOR;

SELECT PROFESSOR_NAME, PROFESSOR_SSN 
FROM TB_PROFESSOR
    JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY 2;

--5. 

SELECT * FROM TB_GRADE;
SELECT * FROM TB_STUDENT;
SELECT * FROM TB_CLASS;


SELECT STUDENT_NO,  LPAD(TO_CHAR(POINT, '9.99'),5) POINT
FROM TB_STUDENT 
    JOIN TB_CLASS  USING (DEPARTMENT_NO)
    JOIN TB_GRADE USING  (STUDENT_NO, CLASS_NO)
WHERE CLASS_NO ='C3118100'
     AND TERM_NO = '200402'
ORDER BY 2 DESC;
   


--6. 

SELECT * FROM TB_STUDENT;
SELECT * FROM TB_DEPARTMENT;

SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
   JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);
   



-- 7. 
SELECT * FROM TB_CLASS;
SELECT * FROM TB_DEPARTMENT;

SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);


-- 8. 

SELECT * FROM TB_CLASS;
SELECT * FROM TB_PROFESSOR;

SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
   JOIN TB_PROFESSOR USING(DEPARTMENT_NO);

   
-- 9.
   
   
SELECT * FROM TB_CLASS;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_DEPARTMENT;

SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
   JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
   JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '인문사회';


-- 10. 



SELECT * FROM TB_STUDENT;
SELECT * FROM TB_GRADE;
SELECT * FROM TB_DEPARTMENT;

SELECT STUDENT_NO 학번, STUDENT_NAME "학생 이름",  ROUND(AVG(POINT),1) "전체 평점"
FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
    JOIN TB_GRADE USING (STUDENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO, STUDENT_NAME 
ORDER BY 1;
   
   

-- 11 .

SELECT * FROM TB_STUDENT;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_PROFESSOR;

SELECT DEPARTMENT_NAME ,STUDENT_NAME, PROFESSOR_NAME
FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
    JOIN TB_PROFESSOR USING  (DEPARTMENT_NO)
WHERE STUDENT_NO = 'A313047';
   

--12 . 
 
 SELECT * FROM TB_STUDENT;
 SELECT * FROM TB_GRADE;
 SELECT * FROM TB_CLASS;
 
 SELECT STUDENT_NAME, TERM_NO
 FROM TB_STUDENT
    JOIN TB_CLASS USING (DEPARTMENT_NO)
    JOIN TB_GRADE USING (STUDENT_NO)
WHERE SUBSTR(TERM_NO,1,4) = '2007'
     AND CLASS_NAME = '인간관계론';


-- 13. 

 SELECT * FROM TB_CLASS;
 SELECT * FROM TB_DEPARTMENT;
 
 
 SELECT CLASS_NAME , DEPARTMENT_NAME
 FROM TB_CLASS
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY ='예체능';


-- 14 .


SELECT * FROM TB_STUDENT;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM tb_professor;

SELECT STUDENT_NAME 학생이름, DECODE(COACH_PROFESSOR_NO , NULL, '지도교수 미지정'
                              , PROFESSOR_NAME ) 지도교수
FROM TB_STUDENT
   JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
   LEFT JOIN tb_professor ON coach_professor_no = PROFESSOR_NO
WHERE DEPARTMENT_NAME = '서반아어학과';


SELECT STUDENT_NAME, COACH_PROFESSOR_NO
FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
    
WHERE DEPARTMENT_NAME = '서반아어학과';
    



